added loggly logging
MHolmes219/DevOps-Course-Starter pull request #13
Opened 2022-11-17 13:21 UTC by MHolmes219

Please make sure you are raising this PR against your own repository and not the original. If it says https://github.com/CorndelWithSoftwire in the search bar right now, you are in the wrong place!

Please also don't forget to submit the PR's url to Aptem afterwards (by clicking on the corresponding exercise component, pasting the url in the textbox that appears and then pressing the finish button).

2022-12-02 12:28 UTC, CorndelWithSoftwireDevOps requested changes
Thanks for submitting the code. The logging infrastructure implementation looks reasonable.
There are few places that still need work.

Adding User ID to the logging will help identify the user with the activity, and it's one of the points on the checklist. There is logging of user attributes (role), but User ID right now missing

The new environment variables are added to `.env.test` config but not the `.env.template`. Make sure your template is up to date with new changes

`README.md` isntruction updates are missing.

nitpick: You could add the screenshot into the PR itself, rather than checking it in. It is not relevant to the codebase.

2022-12-02 12:28 UTC, CorndelWithSoftwireDevOps commented on .env.test
> +LOGGLY_TOKEN=testtoken
You may want to add this setting to the other .env files, so that you can test/perform logging manually

2022-12-02 12:28 UTC, CorndelWithSoftwireDevOps commented on todo_app/app.py
> +        app.logger.info("User is authenticated and their role is %s", User(user_id).role)
You should add User ID to your logging as per submission checklist _Your app has useful logging, using sensible log levels and including information like **user and database ids** where appropriate_

2022-12-02 12:28 UTC, CorndelWithSoftwireDevOps commented on .env.test
> +LOGGLY_TOKEN=testtoken
Make sure LOG_LEVEL is added to the `.env.template` as well

2022-12-02 12:44 UTC, MHolmes219 reviewed
Addressed comments & refactored where appropriate.

2022-12-02 12:45 UTC, MHolmes219 commented
<img width="1515" alt="Screenshot 2022-12-02 at 12 45 17" src="https://user-images.githubusercontent.com/94120411/205295901-32294905-136f-482d-8986-bb6bfae8f67e.png">

2022-12-13 12:26 UTC, CorndelWithSoftwireDevOps requested changes
Your Loggly code and logging looks well. Well done.

There is some setup for Terraform missing because the main is ahead of this exercise branch. This means that your `main` branch deployment will not work as expected if you complete the PR. To avoid this, rebase or merge so that `exercise-13` branch is up to date with `main`, update the terraform setup and finally test the deployment works as expected.

2022-12-13 12:26 UTC, CorndelWithSoftwireDevOps commented on .env.template
> +LOGIN_DISABLED=True
Are you sure you want LOGIN_DISABLED=True as a default behaviour?

2022-12-13 12:26 UTC, CorndelWithSoftwireDevOps commented on todo_app/app.py
> +        app.logger.info("Current card: %s", card[0]['name'])
nitpick: You could use nice modern f-string formatting here and elsewhere `f"Current card: {card[0]['name']}"`

2022-12-13 12:26 UTC, CorndelWithSoftwireDevOps commented on todo_app/flask_config.py
> +        self.LOGGLY_TOKEN = os.environ.get('LOGGLY_TOKEN')
The main is a bit ahead of this `exercise-13` branch. Terraform code is missing in this PR. You will need to update your terraform and make sure it runs, hopefully before merging. Make sure this branch is ahead of `main` by rebasing or merging and update any terraform related setup with new Loggly values

2022-12-13 12:42 UTC, MHolmes219 commented
`No changes. Your infrastructure matches the configuration.

Terraform has compared your real infrastructure against your configuration and found no differences, so no changes are needed.`

2022-12-15 11:07 UTC, CorndelWithSoftwireDevOps approved these changes
Thanks for the update. Everything looks good.

You could add new Loggly environment variables to the Terraform before completing the PR, but it's not required

2022-12-15 12:11 UTC, merged